#ifndef DRV_ERR_DEFS_H_
#define DRV_ERR_DEFS_H_

#define DRV_ERR_NORMAL               0
#define DRV_ERR_THROWER_OVERCURRENT  1
#define DRV_ERR_THROWER_NO_LOAD      2
#define DRV_ERR_THROWER_NOT_DETECTED 3
#define DRV_ERR_DOSING_OVERCURRENT   4
#define DRV_ERR_DOSING_NO_LOAD       5
#define DRV_ERR_DOSING_NOT_DETECTED  6
#define DRV_ERR_POWER_OVERVOLTAGE    7
#define DRV_ERR_POWER_UNDERVOLTAGE   8
#define DRV_ERR_FLOW_NOT_DETECTED    9
#define DRV_NOT_DETECTED             10

#endif // DRV_ERR_DEFS_H_